import Head from "next/head";
import { Inter } from "next/font/google";
import { LiaTshirtSolid } from "react-icons/Lia";
import { PiHoodieLight } from "react-icons/Pi";
import { TbShirtSport } from "react-icons/Tb";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Urban Trends-Wear Your LifeStyle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden">
        <section className="text-gray-600 body-font overflow-x-hidden">
          <div
            className="p-2 bg-green-800 items-center text-center text-green-100 leading-none mx-2 lg:mx-0 rounded-full flex lg:inline-flex overflow-x-hidden"
            role="alert"
          >
            <span className="animate-pulse flex rounded-full bg-green-500 uppercase px-2 py-1 text-xs sm:text-sm lg:text-md font-bold mr-3 text-white">
              New
            </span>
            <span className="font-semibold mr-2 text-left flex-auto text-xs m-auto sm:text-sm lg:text-md">
              Get custom designed products by sending us a text on WhatsApp
            </span>
            <svg
              className="fill-current opacity-75 h-4 w-4"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <path d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z"></path>
            </svg>
          </div>
          <div className="container  py-19 mx-auto">
            <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
              <div id="image" className="flex transition-transform ease-out duration-500 translate-x-0">
                
              </div>
             
              </div>
              </div>
              
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 my-4 text-center text-gray-900">
                Urban Trends-Wear Your LifeStyle<br></br></h1>
                <p className=" text-xl font-medium title-font mb-2 my-4 text-center text-gray-900">Urban fashion, the next big trend</p>
            
            <div className="flex flex-wrap -m-4">
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-4">
                    <button>
                      <LiaTshirtSolid className="text-2xl" />
                    </button>
                  </div>
                  <Link href={"/tshirts"}>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                      TShirts
                    </h2>
                  </Link>
                  <p className="leading-relaxed text-base">
                    Welcome to our T-shirts collection, where style meets
                    comfort in every stitch. Our curated range of tees is
                    designed to be more than just garments – they're a canvas
                    for your self-expression. Each piece in our collection is
                    crafted with care, offering you a perfect blend of quality
                    fabric and unique designs.
                  </p>
                </div>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-4">
                    <button>
                      <PiHoodieLight className="text-2xl" />
                    </button>
                  </div>
                  <Link href={"/hoodies"}>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                      Hoodies
                    </h2>
                  </Link>
                  <p className="leading-relaxed text-base">
                    Step into warmth and style with our Hoodies collection,
                    where comfort meets fashion effortlessly. Our handpicked
                    assortment of hoodies is designed to keep you cozy without
                    compromising on your sense of style. Each hoodie is a
                    testament to our commitment to quality, with attention to
                    detail in every seam and fabric choice. Whether you're
                    looking for a classic, understated design or a bold
                    statement piece, our collection has something for everyone
                  </p>
                </div>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 mb-4">
                    <button>
                      <TbShirtSport className="text-2xl" />
                    </button>
                  </div>
                  <Link href={"/sports"}>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                      Sports OutFit
                    </h2>
                  </Link>
                  <p className="leading-relaxed text-base">
                    Introducing our Sports Outfit collection – where performance
                    meets style to empower your active lifestyle. Dive into a
                    range of athletic apparel meticulously curated to elevate
                    your workout experience. Designed with the perfect blend of
                    functionality and fashion, each piece is crafted to enhance
                    your performance while making a statement.{" "}
                  </p>
                </div>
              </div>
            </div>
        </section>
      </main>
    </>
  );
}
